name = "DEDLoc"
uuid = "38ca6497-7b1e-4b06-a7b8-f466492d3c30"
version = "0.1.0"
authors = ["arne "]

[deps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
GeoParams = "e018b62d-d9de-4a26-8697-af89c310ae38"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
ParallelStencil = "94395366-693c-11ea-3b26-d9b7aac5d958"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
CUDA = "5.9.0"
GeoParams = "0.7.8"
JLD2 = "0.6.2"
LinearAlgebra = "1.12.0"
ParallelStencil = "0.14.3"
Plots = "1.41.1"
Printf = "1.11.0"
Statistics = "1.11.1"
